# Generated by Django 3.0.3 on 2020-02-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='director',
            field=models.BooleanField(default=False, verbose_name='Режиссер'),
        ),
    ]
